### ISSUE TITLE
Calculation and result

### ISSUE THREAD

**Issue by demawi** [Don-Angelo/AreYouTheOneCalculator#4]
Hi!

I have also written calculator for myself.
How do you come to 179.892.000 combinations? Shouldn't it be only 10! * 10 = 36.288.000? (10! are the combinations without Desiree and Desiree additionally can have 10 partners)

After matching night 6 my calculator results in 19 possible combinations instead of 12. 
When looking at Desiree I can't exclude any partner. For her I get the following propabilities: Jordi (42.11), Tim (15.79), Marius (5.26), William (5.26), Mike (5.26), Antonino (5.26), Dustin (5.26), Andre (5.26), Leon (5.26), Max (5.26)
P.e. I can't find a contradiction for the following Desiree&Marius-combination:
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Joelina & Mike
Jessica & Leon
Desiree & Marius
Isabelle & Andre
Raphaela & William
Perhaps you can tell why your calculator can exclude that?

btw. I think the sum of the propabilities for Desiree should result in 100%. Because of Desiree the sum of propabilities for the men should be between 100% (for the first 10 women) and 200% (0-100% additionally for Desiree)

Best regards,
demawi

**Comment by Don-Angelo** [comment]
Hi, 
thanks for your message,
I have so many combinations because i include Desiree. And i dont think the ! operation is the right to calculate all possible combinations. I have tried to calculate it with the combination (https://en.wikipedia.org/wiki/Combination) variant but there is the problem of the order of the pairs wich is irrelevant.

My calculator does not calculates the propabilities. Every pair of a possible combination gets a counter incremented and at the end i calculate the percentage of the overal count of possible combinations for better visability.
I have found out that for good values you need to many data so my progamm focuses on the NOT possible pairs (marked with X) this are the only true and absolute results you can work with. (1% of 10.000 possible combinations are not meaningful enough, only the X counts)

All other excluded pairs i have done per hand starting with Jordie and Monami and checked them for every known matching night.. and so on.

**Comment by Don-Angelo** [comment]
Because of the lack of meaningfulness of the percentage values, i am thinking of removing them and difference only by Possible Not-Possible Perfect-Match and No-Match
Wenn you look at the flucuation of the values it is inappropriate to take them as a indicator with so few matching nights...

Are you caluculating the possibilities? Because i brute force check every combination of the 21 people to get to my results.

Best regards,
Marcel

**Comment by demawi** [comment]
Hi! because the order is irrelevant and we don't have repitition within the first ten persons "!" is the right operation. You can look at a small example: (abc)x(123) this will result in 3! = 6 no repitition and irrelevant order
a1,b2,c3
a1,b3,c2
a2,b1,c3
a2,b3,c1
a3,b1,c2
a3,b2,c1
Desiree also adds only a 10 multiplicator, because the order of the pairs are irrelevant.

Looking into your code. Perhaps you get much more combinations, because you generally said, that a man can have 2 matches. Only Desiree can double a men match-count. So a set like 
Kerstin & Marius
Desiree & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William
shouldn't be valid when creating all possible combinations. Because Kerstin and Zaira are sharing Marius. But this should only be possible with Desiree.

I also create all possible 36.288.000 combinations with an recursive algorithm and test them against the match box and matching night results like your code. Every combination which can't be contradicted is a possible solution. With all those possible solutions the pairs can be counted, how often they occur.
The possiblitiy-calculation from the women side is easy, because they the sum is always 100%: for a women Y: 
_occurence-count-for-women-Y-with-man-X / occurence-count-for-women-Y-with-all-men_.
For men the sum of possiblities are between 100% (not an additional with Desiree) till 200% (Perfect match with Desiree)

If you want a more generous calcuation (in another season the additional person can be a man):
_occurence-count-for-women-Y-with-man-X / occurence-count-for-women-Y-with-first-10-men_
_occurence-count-for-men-X-with-women-Y / occurence-count-for-men-X-with-first-10-women_

I think percentage values are very meaningful, but of course they are only indicator. The chances for the combination in season3-matching night-6 with 4 lights, were only about ~1%. But that's why so much combinations could be erased after that result :)

**Comment by Don-Angelo** [comment]
If i calculate the combination WITH Desiree (as number 4)
(ABC)x(1234)
You get:
A1 B2 C3
A1 B2 C4
A1 B3 C2
A1 B3 C4
A1 B4 C2
A1 B4 C3
A2 B1 C3
A2 B1 C4
A2 B3 C1
A2 B3 C4
A2 B4 C1
A2 B4 C3
A3 B1 C2
A3 B1 C4
A3 B2 C1
A3 B2 C4
A3 B4 C1
A3 B4 C2
A4 B1 C2
A4 B1 C3
A4 B2 C1
A4 B2 C3
A4 B3 C1
A4 B3 C2
This is not just an addition of an 3 (10 with 10 men) multiplicator, because of Desiree there are so many more combinations...

So for me ist was just easy to count all checked combinations rather then calculate them before, because in my eyes with 10 men and 11 women its Not that easy. 

Also my recursive part to select the 10 pairs cant Double a Person (men or women) because every selected Person gets deleated from the lists wich are given to the next Iteration so no one can be selected twice.
If i Look at Dana, she ist now a PM with someone who she had before Just unser 3% (overall, not just referred to that women) this is the reason in my eyes why it makes no really sense to Look at the numbers.

Do you have your code published somewehere?

**Comment by Don-Angelo** [comment]
I have an idea, why the numbers of total checked combinations could bei so high i will check this soon (i think it is a Bug and ist gets not reset)

**Comment by Don-Angelo** [comment]
I have found out why the numbers are that high. I needet to add an function to reset my results for every new inital pair cycle now i have only 24514560 checked combinations anymore and only 4 possible combinations.
Thank you so much for your effort!
This change will result in different values but the main statement of my calculations are the >not possible pairs< wich are not touched/affected by this change 
I fixed it with the newest commit

**Comment by demawi** [comment]
With Desiree as number 4 I would test the following combinations: 3! * 3
a1,b2,c3,a4        a1,b2,c3,b4        a1,b2,c3,c4
a1,b3,c2,a4        a1,b3,c2,b4        a1,b3,c2,c4
a2,b1,c3,a4        a2,b1,c3,b4        a2,b1,c3,c4
a2,b3,c1,a4        a2,b3,c1,b4        a2,b3,c1,c4
a3,b1,c2,a4        a3,b1,c2,b4        a3,b1,c2,c4
a3,b2,c1,a4        a3,b2,c1,b4        a3,b2,c1,c4
We have to test the complete solution, so we have to create 4 pairs instead of 3. With only 3 pairs we're missing some implicit information:
A1 B2 C4 => this means also C3 would be a perfect match. Because only Desirees man can be matched twice. Without this fourth information our contradiction test against the matching nights will produce fail information, when it comes to a test with C3.

When we would test only A1 B2 C3 against our matching nights, we can not derive information about Desirees match and every matching night test with Desiree also will automatically result in useless/unknown assumptions.

I justed created a github-repo for my java code. Mostly interesting should be: https://github.com/demawi/AYTO_Calculator/blob/master/src/demawi/ayto/AYTO_Permutator.java but it isn't optimized yet. But it gives me all needed 36288000 combinations.

After matching night 6 I came to 19 possible solutions left. The same amount https://medium.com/@dirk_32686/are-you-the-one-deutschland-staffel-3-folge-11-und-12-17c15b826a96 calculated. But the given tables on this site aren't completely correct, because he only listed 10 pairs per solution. I also commented the problems on the site.

**Comment by Don-Angelo** [comment]
I do not think i get more informations from testing 4 (11) pairs then from testing 3 (10) because there are only 10 pairs in the MN and i check my combinations how many of the pairs overlap with the pairs in the MN. At the end, i still think that the numbers are irritating (with so frew MN data) and the only valid information is wich pairs are not possible and if you look for not possible pairs it dosent matter if you test with 4(11) or with3(10) 
And it is definitly true that with my approach you might miss some information about Desiree as seen in my calculations of the vip season. There i could not find a possible combination with the 11. women because i only count if a combination is possible based on the matching nights of the episodes and do not calculate chances. I have given up calculating the chances and switched to my brute force approach because i think this is more promising 

I also get frewer as the needet combinations because i test only 10-pair-combinations wich are possible (No matches are not selected for testing) 

i would like to talk to you in discord about this project Don_Angelo#6045

**Comment by demawi** [comment]
We can look at a small example, which shows how a missing pair can led to wrong conclusions:

(a,b,c) (1,2)    3-Pair: Combinations: 2! * 2 = 4
Our **Perfect Match** constellation is: **a1,b2,c1**
MN1: a1,c2 with 1 spot
MN2: a2,c1 with 1 spot
PerfectMatch: b2

**Modelhypothesis (3 pairs approach):**
------------------  MN:a1,c2:1
a1,b2,c1 => 1 spots (the one and only solution)
a1,b2,c2 => 2 spot            
a2,b1,c1 => 0 spot
a2,b1,c2 => 1 spots
-------------------- MN:a2,c1:1
a1,b2,c1 => 1 spot (the one and only solution)
a2,b1,c2 => 1 spot
-------------------- PM:b2
a1,b2,c1 => solution! (the one and only solution)
a2,b1,c2 => no solution! 

**Modelhypothesis (2 pairs approach):**
------------------ MN:a1,c2:1
a1,b2 => 1 spots (solution)
a1,c1 => 1 spots (solution)             
a1,c2 => 2 spot
a2,b1 => 0 spots
a2,c1 => 0 spot           
a2,c2 => 1 spot
b1,c2 => 1 spots
b1,c1 => 0 spots
b2,c1 => 0 spots (solution erased)
b2,c2 => 1 spots
------------------ MN:a2,c1:1
a1,b2 => 0 spots (solution erased)
a1,c1 => 1 spots
a2,c2 => 1 spots
b1,c2 => 0 spots
b2,c2 => 0 spots
------------------ PM:b2
a1,c1 => can not be excluded, missing information about b 
a2,c2 => can not be excluded, missing information about b
Without additional derivation logic, we will never can say anything about b.


**3-pair-combinations can be derived out of the 2-pair-combinations, without missing informations or redundant combinations.**
a1,c1 => (+b2) => a1,b2,c1
a1,c2 => (+b2) => a1,b2,c2
a2,c1 => (+b1) => a2,b1,c1
a2,c2 => (+b1) => a2,b1,c2
a1,b2 => (+c?) => missing model information, we can not say anything about c, unusable. Adding c1 or c2: we already have such an entry.
a2,b1 => (+c?) => missing model information, we can not say anything about c, unusable. Adding c1 or c2: we already have such an entry.
b1,c2 => (+a2) => a2,b1,c2 (redundant combination: we already have that entry) 
b1,c1 => (+a2) => a2,b1,c1 (redundant combination: we already have that entry)  
b2,c1 => (+a1) => a1,b2,c1 (redundant combination: we already have that entry)  
b2,c2 => (+a1) => a1,b2,c2 (redundant combination: we already have that entry)

**Comment by demawi** [comment]
Here are my current results after MN6 if you want to compare:
Berechne AYTO_3 - Nacht 6...
Size: 36288000 Yes: 19 / 0 No: 36287981 Calculation time: 0 min 26 secs Tested intern iterations: 98641010

Potential pairs: 53
Raphaela & William => 78.95% [15/19] Gemeinsame MNs: 2/6
Jessica & Leon => 73.68% [14/19] Gemeinsame MNs: 3/6
Isabelle & Andre => 68.42% [13/19] Gemeinsame MNs: 1/6
Joelina & Mike => 68.42% [13/19] Gemeinsame MNs: 4/6
Kerstin & Tim => 63.16% [12/19] Gemeinsame MNs: 1/6
Zaira & Marius => 57.89% [11/19] Gemeinsame MNs: 1/6
Estelle & Jordi => 57.89% [11/19] Gemeinsame MNs: 1/6
Dana & Antonino => 57.89% [11/19] Gemeinsame MNs: 1/6
Monami & Max => 47.37% [9/19] Gemeinsame MNs: 2/6
Marie & Dustin => 42.11% [8/19] Gemeinsame MNs: 0/6
Desiree & Jordi => 42.11% [8/19] Gemeinsame MNs: 1/6
Zaira & Dustin => 42.11% [8/19] Gemeinsame MNs: 3/6
Estelle & Mike => 31.58% [6/19] Gemeinsame MNs: 2/6
Kerstin & Max => 26.32% [5/19] Gemeinsame MNs: 3/6
Monami & Jordi => 21.05% [4/19] Gemeinsame MNs: 0/6
Marie & Andre => 21.05% [4/19] Gemeinsame MNs: 1/6
Dana & William => 21.05% [4/19] Gemeinsame MNs: 4/6
Monami & Marius => 15.79% [3/19] Gemeinsame MNs: 0/6
Marie & Max => 15.79% [3/19] Gemeinsame MNs: 1/6
Desiree & Tim => 15.79% [3/19] Gemeinsame MNs: 1/6
Raphaela & Jordi => 15.79% [3/19] Gemeinsame MNs: 1/6
Kerstin & Antonino => 10.53% [2/19] Gemeinsame MNs: 2/6
Joelina & Antonino => 10.53% [2/19] Gemeinsame MNs: 0/6
Joelina & Leon => 10.53% [2/19] Gemeinsame MNs: 0/6
Joelina & Tim => 10.53% [2/19] Gemeinsame MNs: 1/6
Marie & Marius => 10.53% [2/19] Gemeinsame MNs: 1/6
Jessica & Antonino => 10.53% [2/19] Gemeinsame MNs: 0/6
Isabelle & Leon => 10.53% [2/19] Gemeinsame MNs: 0/6
Jessica & Tim => 10.53% [2/19] Gemeinsame MNs: 1/6
Dana & Dustin => 10.53% [2/19] Gemeinsame MNs: 0/6
Desiree & Andre => 5.26% [1/19] Gemeinsame MNs: 0/6
Desiree & Max => 5.26% [1/19] Gemeinsame MNs: 0/6
Raphaela & Leon => 5.26% [1/19] Gemeinsame MNs: 0/6
Desiree & William => 5.26% [1/19] Gemeinsame MNs: 0/6
Dana & Tim => 5.26% [1/19] Gemeinsame MNs: 0/6
Desiree & Mike => 5.26% [1/19] Gemeinsame MNs: 0/6
Jessica & Marius => 5.26% [1/19] Gemeinsame MNs: 1/6
Isabelle & Marius => 5.26% [1/19] Gemeinsame MNs: 2/6
Desiree & Antonino => 5.26% [1/19] Gemeinsame MNs: 0/6
Desiree & Dustin => 5.26% [1/19] Gemeinsame MNs: 0/6
Marie & Tim => 5.26% [1/19] Gemeinsame MNs: 2/6
Desiree & Leon => 5.26% [1/19] Gemeinsame MNs: 0/6
Desiree & Marius => 5.26% [1/19] Gemeinsame MNs: 0/6
Monami & Dustin => 5.26% [1/19] Gemeinsame MNs: 0/6
Dana & Andre => 5.26% [1/19] Gemeinsame MNs: 1/6
Estelle & Marius => 5.26% [1/19] Gemeinsame MNs: 0/6
Isabelle & Antonino => 5.26% [1/19] Gemeinsame MNs: 0/6
Monami & Tim => 5.26% [1/19] Gemeinsame MNs: 0/6
Estelle & Max => 5.26% [1/19] Gemeinsame MNs: 0/6
Isabelle & Max => 5.26% [1/19] Gemeinsame MNs: 0/6
Isabelle & Jordi => 5.26% [1/19] Gemeinsame MNs: 0/6
Marie & Antonino => 5.26% [1/19] Gemeinsame MNs: 0/6
Monami & Andre => 5.26% [1/19] Gemeinsame MNs: 0/6

==== Partner ====
**Estelle**: 4 [Jordi (57.89), Mike (31.58), Marius (5.26), Max (5.26), William (0.0), Tim (0.0), Antonino (0.0), Dustin (0.0), Andre (0.0), Leon (0.0)]
**Isabelle**: 6 [Andre (68.42), Leon (10.53), Jordi (5.26), Marius (5.26), Antonino (5.26), Max (5.26), William (0.0), Tim (0.0), Mike (0.0), Dustin (0.0)]
**Dana**: 5 [Antonino (57.89), William (21.05), Dustin (10.53), Tim (5.26), Andre (5.26), Jordi (0.0), Marius (0.0), Mike (0.0), Leon (0.0), Max (0.0)]
**Marie**: 6 [Dustin (42.11), Andre (21.05), Max (15.79), Marius (10.53), Tim (5.26), Antonino (5.26), Jordi (0.0), William (0.0), Mike (0.0), Leon (0.0)]
**Joelina**: 4 [Mike (68.42), Tim (10.53), Antonino (10.53), Leon (10.53), Jordi (0.0), Marius (0.0), William (0.0), Dustin (0.0), Andre (0.0), Max (0.0)]
**Monami**: 6 [Max (47.37), Jordi (21.05), Marius (15.79), Tim (5.26), Dustin (5.26), Andre (5.26), William (0.0), Mike (0.0), Antonino (0.0), Leon (0.0)]
**Zaira**: 2 [Marius (57.89), Dustin (42.11), Jordi (0.0), William (0.0), Tim (0.0), Mike (0.0), Antonino (0.0), Andre (0.0), Leon (0.0), Max (0.0)]
**Raphaela**: 3 [William (78.95), Jordi (15.79), Leon (5.26), Marius (0.0), Tim (0.0), Mike (0.0), Antonino (0.0), Dustin (0.0), Andre (0.0), Max (0.0)]
**Jessica**: 4 [Leon (73.68), Tim (10.53), Antonino (10.53), Marius (5.26), Jordi (0.0), William (0.0), Mike (0.0), Dustin (0.0), Andre (0.0), Max (0.0)]
**Kerstin**: 3 [Tim (63.16), Max (26.32), Antonino (10.53), Jordi (0.0), Marius (0.0), William (0.0), Mike (0.0), Dustin (0.0), Andre (0.0), Leon (0.0)]
**Desiree**: 10 [Jordi (42.11), Tim (15.79), Marius (5.26), William (5.26), Mike (5.26), Antonino (5.26), Dustin (5.26), Andre (5.26), Leon (5.26), Max (5.26)]

**Jordi**: 5 [Estelle (57.89), Desiree (42.11), Monami (21.05), Raphaela (15.79), Isabelle (5.26), Dana (0.0), Marie (0.0), Joelina (0.0), Zaira (0.0), Jessica (0.0), Kerstin (0.0)]
**Marius**: 7 [Zaira (57.89), Monami (15.79), Marie (10.53), Estelle (5.26), Isabelle (5.26), Jessica (5.26), Desiree (5.26), Dana (0.0), Joelina (0.0), Raphaela (0.0), Kerstin (0.0)]
**William**: 3 [Raphaela (78.95), Dana (21.05), Desiree (5.26), Estelle (0.0), Isabelle (0.0), Marie (0.0), Joelina (0.0), Monami (0.0), Zaira (0.0), Jessica (0.0), Kerstin (0.0)]
**Tim**: 7 [Kerstin (63.16), Desiree (15.79), Joelina (10.53), Jessica (10.53), Dana (5.26), Marie (5.26), Monami (5.26), Estelle (0.0), Isabelle (0.0), Zaira (0.0), Raphaela (0.0)]
**Mike**: 3 [Joelina (68.42), Estelle (31.58), Desiree (5.26), Isabelle (0.0), Dana (0.0), Marie (0.0), Monami (0.0), Zaira (0.0), Raphaela (0.0), Jessica (0.0), Kerstin (0.0)]
**Antonino**: 7 [Dana (57.89), Joelina (10.53), Jessica (10.53), Kerstin (10.53), Isabelle (5.26), Marie (5.26), Desiree (5.26), Estelle (0.0), Monami (0.0), Zaira (0.0), Raphaela (0.0)]
**Dustin**: 5 [Marie (42.11), Zaira (42.11), Dana (10.53), Monami (5.26), Desiree (5.26), Estelle (0.0), Isabelle (0.0), Joelina (0.0), Raphaela (0.0), Jessica (0.0), Kerstin (0.0)]
**Andre**: 5 [Isabelle (68.42), Marie (21.05), Dana (5.26), Monami (5.26), Desiree (5.26), Estelle (0.0), Joelina (0.0), Zaira (0.0), Raphaela (0.0), Jessica (0.0), Kerstin (0.0)]
**Leon**: 5 [Jessica (73.68), Isabelle (10.53), Joelina (10.53), Raphaela (5.26), Desiree (5.26), Estelle (0.0), Dana (0.0), Marie (0.0), Monami (0.0), Zaira (0.0), Kerstin (0.0)]
**Max**: 6 [Monami (47.37), Kerstin (26.32), Marie (15.79), Estelle (5.26), Isabelle (5.26), Desiree (5.26), Dana (0.0), Joelina (0.0), Zaira (0.0), Raphaela (0.0), Jessica (0.0)]

==== Beste Konstellationen ====
> Platz 1 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Desiree & Marius
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 2 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Desiree & William
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 3 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William
Desiree & Mike

> Platz 4 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Desiree & Antonino
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 5 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Desiree & Dustin
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 6 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Desiree & Andre
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 7 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Desiree & Leon
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 8 mit 118 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Marie & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Dana & Antonino
Desiree & Max
Joelina & Mike
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 9 mit 109 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Dana & Dustin
Monami & Max
Estelle & Jordi
Zaira & Marius
Desiree & Jordi
Joelina & Mike
Marie & Antonino
Jessica & Leon
Isabelle & Andre
Raphaela & William

> Platz 10 mit 93 Punkten (Summe der Vorkommen der Einzelpaare)
Dana & Dustin
Estelle & Jordi
Zaira & Marius
Monami & Tim
Marie & Max
Desiree & Jordi
Joelina & Mike
Jessica & Leon
Kerstin & Antonino
Isabelle & Andre
Raphaela & William

> Platz 11 mit 92 Punkten (Summe der Vorkommen der Einzelpaare)
Estelle & Jordi
Zaira & Marius
Marie & Max
Dana & Tim
Monami & Dustin
Desiree & Jordi
Joelina & Mike
Jessica & Leon
Kerstin & Antonino
Isabelle & Andre
Raphaela & William

> Platz 12 mit 86 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Isabelle & Max
Dana & Antonino
Desiree & Tim
Joelina & Mike
Zaira & Dustin
Jessica & Leon
Raphaela & William
Monami & Jordi
Estelle & Marius
Marie & Andre

> Platz 13 mit 85 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Monami & Marius
Dana & Antonino
Isabelle & Jordi
Desiree & Tim
Joelina & Mike
Zaira & Dustin
Jessica & Leon
Raphaela & William
Marie & Andre
Estelle & Max

> Platz 14 mit 74 Punkten (Summe der Vorkommen der Einzelpaare)
Kerstin & Tim
Joelina & Antonino
Isabelle & Marius
Estelle & Mike
Marie & Max
Desiree & Jordi
Zaira & Dustin
Jessica & Leon
Raphaela & William
Dana & Andre
Monami & Jordi

> Platz 15 mit 69 Punkten (Summe der Vorkommen der Einzelpaare)
Joelina & Leon
Estelle & Mike
Dana & Antonino
Marie & Tim
Desiree & Tim
Zaira & Dustin
Kerstin & Max
Isabelle & Andre
Raphaela & William
Monami & Jordi
Jessica & Marius

> Platz 16 mit 55 Punkten (Summe der Vorkommen der Einzelpaare)
Jessica & Antonino
Raphaela & Leon
Estelle & Mike
Dana & William
Joelina & Tim
Marie & Marius
Desiree & Jordi
Zaira & Dustin
Kerstin & Max
Isabelle & Andre
Monami & Jordi

> Platz 17 mit 47 Punkten (Summe der Vorkommen der Einzelpaare)
Raphaela & Jordi
Joelina & Antonino
Monami & Marius
Estelle & Mike
Dana & William
Desiree & Jordi
Zaira & Dustin
Kerstin & Max
Isabelle & Leon
Jessica & Tim
Marie & Andre

> Platz 18 mit 46 Punkten (Summe der Vorkommen der Einzelpaare)
Raphaela & Jordi
Monami & Marius
Isabelle & Antonino
Joelina & Leon
Estelle & Mike
Dana & William
Desiree & Jordi
Zaira & Dustin
Kerstin & Max
Jessica & Tim
Marie & Andre

> Platz 19 mit 43 Punkten (Summe der Vorkommen der Einzelpaare)
Jessica & Antonino
Raphaela & Jordi
Estelle & Mike
Dana & William
Joelina & Tim
Marie & Marius
Desiree & Jordi
Zaira & Dustin
Kerstin & Max
Monami & Andre
Isabelle & Leon

**Comment by demawi** [comment]
Matching Night 6 constellation
Possible constellations before: 1859
Spot probabilities 0 => 5.43 [101]
Spot probabilities 1 => 61.27 [1139]
Spot probabilities 2 => 25.87 [481]
Spot probabilities 3 => 6.35 [118]
Spot probabilities 4 => 1.02 [19]
Spot probabilities 5 => 0.05 [1]
Spot probabilities 6 => 0.0 [0]
Spot probabilities 7 => 0.0 [0]
Spot probabilities 8 => 0.0 [0]
Spot probabilities 9 => 0.0 [0]
Spot probabilities 10 => 0.0 [0]
They got 4 spots. This had only a 1,02% chance. But all the better, with that they only have 19 constellations left.

**Comment by Don-Angelo** [comment]
Updated the AYTO-Calculator to v3 wich now gets the same results
